import type { Activity, Material, Student, VocabularyItem } from "@/types/domain";

export const students: Student[] = [
  {
    id: "maya",
    firstName: "Maya",
    initials: "MC",
    color: "#e8a06f",
    communicationMode: "Symbols + text",
    prioritySupport: "One-step directions",
    grid: "3 × 4",
    processingTime: 8,
    currentActivity: "Science",
    symbolProvider: "arasaac",
  },
  {
    id: "leo",
    firstName: "Leo",
    initials: "LR",
    color: "#74a99b",
    communicationMode: "Photos + symbols",
    prioritySupport: "Visible turn-taking",
    grid: "2 × 3",
    processingTime: 10,
    currentActivity: "Morning meeting",
    symbolProvider: "custom",
  },
  {
    id: "noah",
    firstName: "Noah",
    initials: "NB",
    color: "#8187c6",
    communicationMode: "Text + speech",
    prioritySupport: "Transition preview",
    grid: "4 × 5",
    processingTime: 5,
    currentActivity: "Reading",
    symbolProvider: "arasaac",
  },
];

export const activities: Activity[] = [
  {
    id: "science",
    time: "10:00 AM",
    title: "Group science experiment",
    students: ["Maya", "Leo"],
    context: "Room 14",
    status: "needs-supports",
  },
  {
    id: "reading",
    time: "11:15 AM",
    title: "Shared reading circle",
    students: ["Noah"],
    context: "Library corner",
    status: "ready",
  },
  {
    id: "lunch",
    time: "12:10 PM",
    title: "Transition to lunch",
    students: ["Maya", "Leo", "Noah"],
    context: "Main hallway",
    status: "in-progress",
  },
];

export const materials: Material[] = [
  {
    id: "fruit-salad-board",
    title: "Fruit Salad Communication Board",
    type: "Communication board",
    student: "Maya",
    status: "published",
    edited: "Today, 8:42 AM",
    symbolProvider: "ARASAAC",
  },
  {
    id: "science-sequence",
    title: "Science Experiment Sequence",
    type: "Visual sequence",
    student: "Maya + Leo",
    status: "review",
    edited: "Today, 7:55 AM",
    symbolProvider: "Mixed",
  },
  {
    id: "indoor-recess",
    title: "Indoor Recess Change Card",
    type: "Transition support",
    student: "Noah",
    status: "draft",
    edited: "Yesterday",
    symbolProvider: "ARASAAC",
  },
  {
    id: "sub-passport",
    title: "Substitute Teacher Passport",
    type: "Communication passport",
    student: "Leo",
    status: "published",
    edited: "Jul 16",
    symbolProvider: "Custom photos",
  },
];

export const vocabulary: VocabularyItem[] = [
  {
    id: "i",
    label: "I",
    kind: "core",
    stablePosition: 0,
    category: "core",
    usageCount: 48,
    activityAffinity: { science: 0.5, "fruit-salad": 0.5 },
  },
  {
    id: "want",
    label: "want",
    arasaacId: 5441,
    kind: "core",
    stablePosition: 1,
    category: "core",
    usageCount: 41,
    activityAffinity: { science: 0.7, "fruit-salad": 0.7 },
  },
  {
    id: "more",
    label: "more",
    arasaacId: 5508,
    kind: "core",
    stablePosition: 2,
    category: "core",
    usageCount: 37,
  },
  {
    id: "different",
    label: "different",
    arasaacId: 4628,
    kind: "core",
    stablePosition: 3,
    category: "core",
    usageCount: 18,
  },
  {
    id: "like",
    label: "like",
    arasaacId: 2418,
    kind: "core",
    stablePosition: 4,
    category: "core",
    usageCount: 22,
  },
  {
    id: "go",
    label: "go",
    arasaacId: 2432,
    kind: "core",
    stablePosition: 5,
    category: "core",
    usageCount: 33,
  },
  {
    id: "help",
    label: "help",
    arasaacId: 4570,
    kind: "safety",
    stablePosition: 6,
    category: "core",
    usageCount: 12,
  },
  {
    id: "stop",
    label: "stop",
    arasaacId: 2499,
    kind: "safety",
    stablePosition: 7,
    category: "core",
    usageCount: 16,
  },
  {
    id: "banana",
    label: "banana",
    arasaacId: 2530,
    kind: "fringe",
    category: "food",
    usageCount: 8,
    lastUsedMinutesAgo: 12,
    activityAffinity: { "fruit-salad": 1 },
    timeAffinity: { morning: 0.2, midday: 0.8, afternoon: 0.2 },
    personalRelevance: 0.8,
  },
  {
    id: "apple",
    label: "apple",
    arasaacId: 2462,
    kind: "fringe",
    category: "food",
    usageCount: 13,
    lastUsedMinutesAgo: 8,
    activityAffinity: { "fruit-salad": 1 },
    timeAffinity: { morning: 0.3, midday: 0.9, afternoon: 0.2 },
    personalRelevance: 0.9,
  },
  {
    id: "bowl",
    label: "bowl",
    arasaacId: 3257,
    kind: "fringe",
    category: "food",
    usageCount: 4,
    activityAffinity: { "fruit-salad": 1, science: 0.2 },
    personalRelevance: 0.4,
  },
  {
    id: "cut",
    label: "cut",
    arasaacId: 5484,
    kind: "fringe",
    category: "actions",
    usageCount: 9,
    activityAffinity: { "fruit-salad": 1 },
    personalRelevance: 0.5,
  },
  {
    id: "mix",
    label: "mix",
    arasaacId: 5515,
    kind: "fringe",
    category: "actions",
    usageCount: 6,
    activityAffinity: { "fruit-salad": 1, science: 0.4 },
    personalRelevance: 0.6,
  },
  {
    id: "my-turn",
    label: "my turn",
    arasaacId: 6006,
    kind: "fringe",
    category: "actions",
    usageCount: 19,
    activityAffinity: { "fruit-salad": 0.9, science: 0.9 },
    personalRelevance: 0.8,
  },
  {
    id: "break",
    label: "break",
    arasaacId: 3369,
    kind: "safety",
    category: "core",
    usageCount: 11,
    activityAffinity: { "fruit-salad": 0.4, science: 0.4 },
    personalRelevance: 1,
  },
  {
    id: "teacher",
    label: "teacher",
    arasaacId: 2457,
    kind: "fringe",
    category: "people",
    usageCount: 7,
    personalRelevance: 0.8,
  },
  {
    id: "friend",
    label: "friend",
    arasaacId: 8486,
    kind: "fringe",
    category: "people",
    usageCount: 5,
    personalRelevance: 0.7,
  },
  {
    id: "happy",
    label: "happy",
    arasaacId: 3245,
    kind: "fringe",
    category: "feelings",
    usageCount: 6,
  },
  {
    id: "sad",
    label: "sad",
    arasaacId: 2606,
    kind: "fringe",
    category: "feelings",
    usageCount: 4,
  },
  {
    id: "eat",
    label: "eat",
    arasaacId: 2349,
    kind: "fringe",
    category: "food",
    usageCount: 8,
    activityAffinity: { "fruit-salad": 0.9 },
  },
  {
    id: "drink",
    label: "drink",
    arasaacId: 2276,
    kind: "fringe",
    category: "food",
    usageCount: 6,
  },
  {
    id: "school",
    label: "school",
    arasaacId: 3082,
    kind: "fringe",
    category: "school",
    usageCount: 5,
  },
  {
    id: "toilet",
    label: "toilet",
    arasaacId: 2430,
    kind: "safety",
    category: "school",
    usageCount: 5,
  },
  {
    id: "yes",
    label: "yes",
    arasaacId: 5583,
    kind: "core",
    category: "core",
    usageCount: 14,
  },
  {
    id: "no",
    label: "no",
    arasaacId: 5525,
    kind: "safety",
    category: "core",
    usageCount: 15,
  },
  {
    id: "pain",
    label: "pain",
    arasaacId: 2367,
    kind: "safety",
    category: "core",
    usageCount: 2,
  },
  {
    id: "wait",
    label: "wait",
    arasaacId: 8109,
    kind: "core",
    category: "actions",
    usageCount: 11,
  },
  {
    id: "play",
    label: "play",
    arasaacId: 2439,
    kind: "fringe",
    category: "actions",
    usageCount: 9,
  },
  {
    id: "choose",
    label: "choose",
    arasaacId: 6483,
    kind: "fringe",
    category: "actions",
    usageCount: 8,
  },
  {
    id: "fruit",
    label: "fruit",
    arasaacId: 28339,
    kind: "fringe",
    category: "food",
    usageCount: 7,
    activityAffinity: { "fruit-salad": 1 },
  },
  {
    id: "put",
    label: "put",
    arasaacId: 5447,
    kind: "fringe",
    category: "actions",
    usageCount: 6,
    activityAffinity: { "fruit-salad": 1 },
  },
  {
    id: "finished",
    label: "finished",
    arasaacId: 5358,
    kind: "core",
    category: "core",
    usageCount: 12,
  },
  {
    id: "wake",
    label: "wake up",
    arasaacId: 8988,
    kind: "fringe",
    category: "actions",
    usageCount: 2,
  },
  {
    id: "hello",
    label: "hello",
    arasaacId: 6009,
    kind: "core",
    category: "core",
    usageCount: 8,
  },
  {
    id: "book",
    label: "book",
    arasaacId: 2450,
    kind: "fringe",
    category: "school",
    usageCount: 10,
  },
  {
    id: "read",
    label: "read",
    arasaacId: 5973,
    kind: "fringe",
    category: "actions",
    usageCount: 9,
  },
  {
    id: "music",
    label: "music",
    arasaacId: 24795,
    kind: "fringe",
    category: "school",
    usageCount: 11,
  },
];
